### ISSUE TITLE
出错这样的错误 怎么解决

### ISSUE THREAD

**Issue by jiji262** [knightingal/SimpleDownloader#1]
```
......
start downloading http://static.wooyun.org/201405/2014050416283391280.jpg
start downloading http://static.wooyun.org/201405/2014050416285879868.jpg
start downloading http://static.wooyun.org/201405_http_client.js:25
      throw new Error('Unable to determine the domain name');
      ^

Error: Unable to determine the domain name
    at new ClientRequest (_http_client.js:25:13)
    at Object.exports.request (http.js:31:10)
```

**Comment by knightingal** [comment]
‘Unable to determine the domain name’意思是域名解析有问题，请检查一下你的dns配置。
或者你是不是在某个内网环境中，需要配置proxy才能连接外网，需要查看nodejs的相关api文档了。

**Comment by jiji262** [comment]
好像不是你说的情况。上面的一系列图片都已经下载完成了。

难道是因为我的数组太大了？？

如果是的话 怎么解决呢

**Comment by knightingal** [comment]
应该不会数组太大，既然图片已经下载下来，说明可能只是某个url有问题，你可是先删除大部分url，只保留一条，看看代码是否报错，如果不报错，再逐步增加url，直到出现报错为止，然后再仔细检查这个出错的url问题在哪里。

**Comment by jiji262** [comment]
单个url没有问题，而且每次断的地方不一样。

**Comment by jiji262** [comment]
完整代码在这里：
https://github.com/jiji262/wooyun_articles/blob/gh-pages/code/down2.js

麻烦看下 谢谢

**Comment by knightingal** [comment]
这里面夹杂了6个https链接，需要用https模块，`const https = require('https');`，和http差不多，具体的参考官方文档。

还有类似这样的链接
`'data:image/gif;base64,R0lGODlhBAADAPAAAP%2F%2F%2FwAAACH%2FC1hNUCBEYXRhWE1QAz94cAAh%2BQQFAAAAACwAAAAABAADAAACA4SPVgA7'`
也会报错

剔除掉上面提到的这两种有问题的链接，我试着跑了一下，这一万多个链接最终下载成功8783个图片，有一些死链接，需要在代码里做重试次数限制，估计还有一些重复的链接，也需要另外处理。

**Comment by jiji262** [comment]
有时候会发现目录下没有下载成功的文件，目录具有可写权限，有时候有这样的错误：

```
tart downloading http://static.wooyun.org//drops/20151225/2015122505044680079528.png
request http://static.wooyun.org//drops/20151225/2015122505045217078921.png error, try again
start downloading http://static.wooyun.org//drops/20151225/2015122505045217078921.png
request http://static.wooyun.org//drops/20151225/20151225050456386661218.png error, try again
start downloading http://static.wooyun.org//drops/20151225/20151225050456386661218.png
request http://static.wooyun.org//drops/20160118/2016011804524482635520.png error, try again
start downloading http://static.wooyun.org//drops/20160118/2016011804524482635520.png
request http://static.wooyun.org//drops/20160118/2016011804524160465322.png error, try again
start downloading http://static.wooyun.org//drops/20160118/2016011804524160465322.png
request http://static.wooyun.org//drops/20160118/2016011804525037386815.png error, try again
start downloading http://static.wooyun.org//drops/20160118/2016011804525037386815.png
request http://static.wooyun.org//drops/20160118/2016011804524841803715.png error, try again
start downloading http://static.wooyun.org//drops/20160118/2016011804524841803715.png
request http://static.wooyun.org//drops/20160411/2016041114510479175119.jpg error, try again
start downloading http://static.wooyun.org//drops/20160411/2016041114510479175119.jpg
request http://static.wooyun.org//drops/20160411/201604111451152365677.jpg error, try again
start downloading http://static.wooyun.org//drops/20160411/201604111451152365677.jpg
```

**Comment by knightingal** [comment]
这个问题我没有复现出来

```
start downloading http://static.wooyun.org//drops/20151225/2015122505045217078921.png
start downloading http://static.wooyun.org//drops/20151225/20151225050456386661218.png
start downloading http://static.wooyun.org//drops/20160118/2016011804524482635520.png
start downloading http://static.wooyun.org//drops/20160118/2016011804524160465322.png
start downloading http://static.wooyun.org//drops/20160118/2016011804525037386815.png
start downloading http://static.wooyun.org//drops/20160118/2016011804524841803715.png
start downloading http://static.wooyun.org//drops/20160411/2016041114510479175119.jpg
start downloading http://static.wooyun.org//drops/20160411/201604111451152365677.jpg
request: http://static.wooyun.org//drops/20160118/2016011804524482635520.png return status: 200
end downloading http://static.wooyun.org//drops/20160118/2016011804524482635520.png
totalBuff.length = 12608 contentLength = 12608
request: http://static.wooyun.org//drops/20151225/2015122505045217078921.png return status: 200
end downloading http://static.wooyun.org//drops/20151225/2015122505045217078921.png
totalBuff.length = 13969 contentLength = 13969
request: http://static.wooyun.org//drops/20160118/2016011804524841803715.png return status: 200
end downloading http://static.wooyun.org//drops/20160118/2016011804524841803715.png
totalBuff.length = 20271 contentLength = 20271
request: http://static.wooyun.org//drops/20151225/20151225050456386661218.png return status: 200
end downloading http://static.wooyun.org//drops/20151225/20151225050456386661218.png
totalBuff.length = 16161 contentLength = 16161
request: http://static.wooyun.org//drops/20160118/2016011804525037386815.png return status: 200
end downloading http://static.wooyun.org//drops/20160118/2016011804525037386815.png
totalBuff.length = 23631 contentLength = 23631
request: http://static.wooyun.org//drops/20160411/201604111451152365677.jpg  return status: 200
request: http://static.wooyun.org//drops/20160118/2016011804524160465322.png return status: 200
end downloading http://static.wooyun.org//drops/20160118/2016011804524160465322.png
totalBuff.length = 6082 contentLength = 6082
request: http://static.wooyun.org//drops/20160411/2016041114510479175119.jpg return status: 200
end downloading http://static.wooyun.org//drops/20160411/201604111451152365677.jpg
totalBuff.length = 147331 contentLength = 147331
end downloading http://static.wooyun.org//drops/20160411/2016041114510479175119.jpg
totalBuff.length = 146292 contentLength = 146292

```

```
$ ls
0-2015122505045217078921.png   2-2016011804524482635520.png  4-2016011804525037386815.png  6-2016041114510479175119.jpg  index.js      PromisDownloader.md
1-20151225050456386661218.png  3-2016011804524160465322.png  5-2016011804524841803715.png  7-201604111451152365677.jpg   package.json
```

很抱歉这个问题我暂时帮不到你了。可能是同时发起的连接数量太多导致的，或者乌云服务器对你的ip启动了反爬，你可以在代码里面限制一下并发连接数量，看看有没有帮助。
